# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

resources:
  containers:
  - container: sdk5
    image: mcr.microsoft.com/dotnet/sdk:5.0   
  - container: sonarscanner
    image: sonarsource/sonar-scanner-cli:latest

variables:
  buildConfiguration: 'Release'
  SONARQUBE_URL: 'https://sonarqube-1749-3725.dc-ig-lib-ga-1589529604-f72ef11f3ab089a8c677044eb28292cd-0000.au-syd.containers.appdomain.cloud'
  NAMESPACE: 'dc-apps'
  K8S_DEPLOYMENT: 'dotnet'
  
jobs:
- job: build
  container: sdk5
  steps:
  - script: dotnet restore
  - script: dotnet publish -c Release -o out
  
- job: sonarscan
  container: sonarscanner
  steps:
  - script: pwd
  - script: ls -ltr
  - script: mkdir .sonar .sonar/cache .scannerwork
  - script: chmod -R 777 .sonar
  - script: chmod -R 777 .scannerwork
  - script: sonar-scanner \
            -Dsonar.host.url=${SONARQUBE_URL} \                 
            -Dsonar.projectKey=${NAMESPACE}-${K8S_DEPLOYMENT} \         
            -Dsonar.sources=. \        
            -Dsonar.projectVersion=1\           
            -Dsonar.exclusions=node_modules/**            
                      
                       



#steps:
#- script: dotnet build --configuration $(buildConfiguration)
 # displayName: 'dotnet build $(buildConfiguration)'
