# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

resources:
  containers:
  - container: sdk5
    image: mcr.microsoft.com/dotnet/sdk:5.0   

variables:
  buildConfiguration: 'Release'
  
jobs:
- job: build
  container: sdk5
  steps:
  - script: dotnet restore
  - script: dotnet publish -c Release -o out



#steps:
#- script: dotnet build --configuration $(buildConfiguration)
 # displayName: 'dotnet build $(buildConfiguration)'
